# Generated by Django 4.2.5 on 2023-10-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/img/banner/')),
            ],
        ),
    ]
