# Generated by Django 4.2.5 on 2023-10-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img/banner/')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='img/banner/'),
        ),
        migrations.AlterField(
            model_name='category_1',
            name='image',
            field=models.ImageField(upload_to='img/banner/'),
        ),
    ]
