# Generated by Django 4.2.5 on 2023-10-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_2_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('day', models.DateTimeField(max_length=50)),
                ('hour', models.DateTimeField(max_length=50)),
                ('minute', models.DateTimeField(max_length=50)),
                ('second', models.DateTimeField(max_length=50)),
            ],
        ),
    ]
