# Generated by Django 4.2.5 on 2023-10-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sale_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_of',
            name='day',
            field=models.TimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale_of',
            name='hour',
            field=models.TimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale_of',
            name='minute',
            field=models.TimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale_of',
            name='second',
            field=models.TimeField(max_length=50),
        ),
    ]
