# Generated by Django 4.2.5 on 2023-10-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_sale_of_day_alter_sale_of_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_of',
            name='image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
