# Generated by Django 4.2.5 on 2023-10-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sale_of_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_of',
            name='day',
            field=models.DurationField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale_of',
            name='hour',
            field=models.DurationField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale_of',
            name='minute',
            field=models.DurationField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale_of',
            name='second',
            field=models.DurationField(max_length=50),
        ),
    ]
