# Generated by Django 4.2.5 on 2023-10-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_sale_of_day_alter_sale_of_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_of',
            name='day',
        ),
        migrations.RemoveField(
            model_name='sale_of',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='sale_of',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='sale_of',
            name='second',
        ),
    ]
