# Generated by Django 4.2.5 on 2023-10-27 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_sale_of_day_remove_sale_of_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_of',
            name='day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale_of',
            name='hour',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_of',
            name='minute',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_of',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_of',
            name='second',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
