# Generated by Django 4.2.5 on 2023-10-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sale_of_day_sale_of_hour_sale_of_minute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale_of',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='sale_of',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='sale_of',
            name='second',
        ),
        migrations.AlterField(
            model_name='sale_of',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
