# Generated by Django 4.2.5 on 2023-10-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_sale_of_hour_remove_sale_of_minute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='img/instagram')),
                ('image_2', models.ImageField(upload_to='img/instagram')),
                ('image_3', models.ImageField(upload_to='img/instagram')),
                ('image_4', models.ImageField(upload_to='img/instagram')),
                ('image_5', models.ImageField(upload_to='img/instagram')),
                ('image_6', models.ImageField(upload_to='img/instagram')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sale_of',
            name='image',
            field=models.ImageField(upload_to='img/product_sale'),
        ),
    ]
