# Generated by Django 4.2.5 on 2023-10-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_instagram_alter_sale_of_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('image_1', models.ImageField(upload_to='img/blog')),
                ('description_1', models.CharField(max_length=100)),
                ('image_2', models.ImageField(upload_to='img/blog')),
                ('description_2', models.CharField(max_length=100)),
                ('image_3', models.ImageField(upload_to='img/blog')),
                ('description_3', models.CharField(max_length=100)),
            ],
        ),
    ]
