# Generated by Django 4.2.5 on 2023-10-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_latest_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_news',
            name='date_1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latest_news',
            name='date_2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latest_news',
            name='date_3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
