# Generated by Django 4.2.5 on 2023-10-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_latest_news_date_1_latest_news_date_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
