# Generated by Django 4.2.5 on 2023-10-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_newletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newletter',
            old_name='email',
            new_name='email1',
        ),
    ]
