# Generated by Django 4.2.5 on 2023-10-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_email_newletter_email1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newletter',
            old_name='email1',
            new_name='email',
        ),
    ]
