# Generated by Django 4.2.5 on 2023-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_email1_newletter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image_1', models.ImageField(upload_to='img/hero/')),
                ('image_2', models.ImageField(upload_to='img/hero/')),
            ],
        ),
    ]
