# Generated by Django 4.2.5 on 2023-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_index_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_1', models.ImageField(upload_to='img/logo')),
                ('logo_2', models.ImageField(upload_to='img/logo')),
            ],
        ),
    ]
