# Generated by Django 4.2.5 on 2023-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo_1',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo_2',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
