# Generated by Django 4.2.5 on 2023-10-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_logo_logo_1_alter_logo_logo_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='logo_3',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
