# Generated by Django 4.2.5 on 2023-10-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_logo_logo_3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category_1',
        ),
        migrations.DeleteModel(
            name='category_2',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_1',
        ),
        migrations.AddField(
            model_name='category',
            name='image_2',
            field=models.ImageField(default=1, upload_to='img/banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image_3',
            field=models.ImageField(default=1, upload_to='img/banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
