# Generated by Django 4.2.5 on 2023-10-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_delete_category_1_delete_category_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='colour_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='filter_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('200  TO 250', '250 TO 300'), ('300 TO 650', '400 TO 550'), ('550 TO 650', '650 TO 700'), ('700 TO 850', '850 TO 100')], max_length=60)),
            ],
        ),
    ]
