# Generated by Django 4.2.5 on 2023-10-28 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_colour_product_filter_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(upload_to='img/product/')),
                ('name', models.CharField(max_length=200)),
                ('print', models.IntegerField()),
                ('condition', models.CharField(choices=[('New', 'New'), ('old', 'old')], max_length=100)),
                ('stock', models.CharField(choices=[('SALE', 'SALE'), ('NEW', 'NEW'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=50)),
                ('created_date', models.CharField(default=django.utils.timezone.now, max_length=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.colour_product')),
                ('filter_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filter_price')),
            ],
        ),
    ]
