# Generated by Django 4.2.5 on 2023-10-28 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
