# Generated by Django 4.2.5 on 2023-10-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_shop_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_shop',
            old_name='print',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product_shop',
            name='condition',
        ),
        migrations.AddField(
            model_name='product_shop',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_shop',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
