# Generated by Django 4.2.5 on 2023-10-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_rename_print_product_shop_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_3',
        ),
    ]
