# Generated by Django 4.2.5 on 2023-10-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_category_image_2_remove_category_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_2',
            field=models.ImageField(default=1, upload_to='img/banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image_3',
            field=models.ImageField(default=1, upload_to='img/banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
