# Generated by Django 4.2.5 on 2023-10-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_category_image_2_category_image_3_category_name_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=50)),
                ('image_1', models.ImageField(upload_to='img/banner/')),
            ],
        ),
        migrations.CreateModel(
            name='category_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=50)),
                ('image_1', models.ImageField(upload_to='img/banner/')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_3',
        ),
    ]
