# Generated by Django 4.2.5 on 2023-10-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_category_1_category_2_remove_category_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_shop',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category_2'),
        ),
    ]
