# Generated by Django 4.2.5 on 2023-10-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_shop_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_shop',
            name='categories',
        ),
    ]
