# Generated by Django 4.2.5 on 2023-10-28 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_remove_product_shop_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_shop',
            name='stock',
        ),
        migrations.AddField(
            model_name='product_shop',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
