# Generated by Django 4.2.5 on 2023-10-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_shop_stock_product_shop_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category_1',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category_1',
            old_name='name_1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category_2',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category_2',
            old_name='name_1',
            new_name='name',
        ),
    ]
