# Generated by Django 4.2.5 on 2023-10-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_rename_image_1_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_shop',
            name='categories',
        ),
    ]
