# Generated by Django 4.2.5 on 2023-10-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_product_shop_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_shop',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product_shop',
            name='filter_p',
        ),
        migrations.AddField(
            model_name='product_shop',
            name='stock',
            field=models.CharField(choices=[('SALE', 'SALE'), ('NEW', 'NEW'), ('OUT OF STOCK', 'OUT OF STOCK')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='colour_product',
        ),
        migrations.DeleteModel(
            name='filter_price',
        ),
    ]
