# Generated by Django 4.2.5 on 2023-10-29 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_product_shop_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shop',
            name='created_date_1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product_shop',
            name='description_1',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_shop',
            name='image_1',
            field=models.ImageField(default=1, upload_to='img/product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_shop',
            name='name_1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_shop',
            name='price_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_shop',
            name='stock_1',
            field=models.CharField(choices=[('SALE', 'SALE'), ('NEW', 'NEW'), ('OUT OF STOCK', 'OUT OF STOCK')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
