# Generated by Django 4.2.5 on 2023-10-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_product_shop_created_date_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_shop',
            name='created_date_1',
        ),
        migrations.RemoveField(
            model_name='product_shop',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='product_shop',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='product_shop',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='product_shop',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='product_shop',
            name='stock_1',
        ),
    ]
