# Generated by Django 4.2.5 on 2023-11-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_customer_order_product_shop_digital_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_shop',
            new_name='Product',
        ),
    ]
