# Generated by Django 4.2.5 on 2023-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_order_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=200)),
                ('description_1', models.CharField(max_length=200)),
                ('title_2', models.CharField(max_length=200)),
                ('description_2', models.CharField(max_length=250)),
                ('title_3', models.CharField(max_length=200)),
                ('description_3', models.CharField(max_length=250)),
                ('phone_1', models.CharField(max_length=50)),
                ('phone_2', models.CharField(max_length=50)),
            ],
        ),
    ]
