# Generated by Django 4.2.5 on 2023-11-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_contact_us_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
