# Generated by Django 4.2.5 on 2023-11-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_contact_us_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(default='img/profile/default.png', upload_to='img/profile/'),
        ),
    ]
