# Generated by Django 4.2.5 on 2023-11-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_alter_customer_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(blank=True, default='img/profile/default1.png', null=True, upload_to='img/profile/'),
        ),
    ]
