# Generated by Django 4.2.5 on 2023-11-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_customer_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer'),
        ),
    ]
