# Generated by Django 4.2.5 on 2023-11-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_order_item_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='customer',
        ),
    ]
