# Generated by Django 4.2.5 on 2023-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_remove_order_item_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image_title', models.ImageField(upload_to='img/blog/details')),
                ('description_1', models.CharField(max_length=300)),
                ('description_2', models.CharField(max_length=300)),
                ('writer_name', models.CharField(max_length=20)),
                ('image_writer', models.ImageField(upload_to='img/blog/details')),
                ('hashtag_1', models.CharField(max_length=20)),
                ('hashtag_2', models.CharField(max_length=20)),
                ('hashtag_3', models.CharField(max_length=20)),
            ],
        ),
    ]
