# Generated by Django 4.2.5 on 2023-11-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_leave_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_comment',
            name='description_1',
            field=models.CharField(max_length=500),
        ),
    ]
