# Generated by Django 4.2.5 on 2023-11-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_alter_leave_comment_description_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
