# Generated by Django 4.2.5 on 2023-11-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_send_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='img/about/')),
                ('title_1', models.CharField(max_length=50)),
                ('description_1', models.CharField(max_length=500)),
                ('title_2', models.CharField(max_length=50)),
                ('description_2', models.CharField(max_length=500)),
                ('title_3', models.CharField(max_length=50)),
                ('description_3', models.CharField(max_length=500)),
            ],
        ),
    ]
