# Generated by Django 4.2.5 on 2023-11-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='img/about/')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='aboutus',
            name='author_department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='author_img',
            field=models.ImageField(default=1, upload_to='img/about/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='author_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='blog_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='blog_img',
            field=models.ImageField(default=1, upload_to='img/about/'),
            preserve_default=False,
        ),
    ]
