# Generated by Django 4.2.5 on 2023-11-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_team_members_aboutus_author_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_members',
            name='title',
        ),
    ]
