# Generated by Django 4.2.5 on 2023-11-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_shippingaddress_product_delete_whole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='product',
        ),
    ]
